### ISSUE TITLE
Camera Preview is not showing

### ISSUE THREAD

**Issue by AlexTerry1024** [spoonconsulting/cordova-plugin-simple-camera-preview#70]
Hello, How are you?

When I execute enable command, I think the camera is started correctly, but I can't see any camera preview

**Comment by dinitri** [comment]
Hello @AlexTerry1024 

Please make sure you added the following styling as per the READ.ME

```
html, body, .ion-app, .ion-content {
  background-color: transparent;
}
```

**Comment by J4tinP** [comment]
Hello @AlexTerry1024 

Did this resolve your issue?
